export const MaterialTypePhong = 'MaterialPhong'
export const MaterialTypeBasic = 'MaterialBasic'
export const MaterialTypeToon = 'MaterialToon'
export const INPUT_GAMEPAD = 'GAMEPAD'
export const INPUT_KEYBOARD = 'KEYBOARD'
